name: 友链申请
description: 申请添加友链
title: "[友链] "
labels: ["友链申请"]
body:
  - type: markdown
    attributes:
      value: |
        ## 友链申请须知
        
        - 请确保您的站点内容健康，无违法违规信息
        - 请确保您的站点可以正常访问
        - 建议先添加本站友链后再提交申请
        
        **本站友链信息：**
        - 站点名称：Mininano
        - 站点地址：https://your-domain.com
        - 站点描述：个人博客 - 工作生活记录、折腾备忘
        - 头像地址：https://your-domain.com/avatar.webp
        - RSS地址：https://your-domain.com/atom.xml
  
  - type: textarea
    id: link_info
    attributes:
      label: 友链信息
      description: 请按照以下 JSON 格式填写您的友链信息
      placeholder: |
        {
          "title": "站点名称",
          "url": "https://example.com",
          "screenshot": "https://example.com/avatar.png",
          "description": "一句话介绍你的站点",
          "feed": "https://example.com/atom.xml"
        }
      value: |
        ```json
        {
          "title": "",
          "url": "",
          "screenshot": "",
          "description": "",
          "feed": ""
        }
        ```
    validations:
      required: true
  
  - type: checkboxes
    id: terms
    attributes:
      label: 确认事项
      options:
        - label: 我已添加贵站友链
          required: false
        - label: 我的站点内容健康，无违法违规信息
          required: true
        - label: 我的站点可以正常访问
          required: true
        - label: 我已提供有效的 RSS/Atom 订阅地址
          required: false
